from clearest import *
from tests.wsgi import WSGITestCase


def strip_ws(source):
    return source.strip(" \t\n\r")


class Test(WSGITestCase):
    def setUp(self):
        unregister_all()

    @property
    def test_docs(self):
        @GET("/asd")
        def asd():
            """asd"""
            return {}

        result = self.get("/asd", accept="text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
        self.assertEqual(HTTP_OK, self.status)
        self.assertTrue(CONTENT_TYPE in self.headers)
        self.assertEqual(MIME_XHTML_XML, self.headers[CONTENT_TYPE])
        self.assertEqual(strip_ws("""
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Title</title>
    </head>
    <body>
        <div id="content">
            GET
            /asd
            asd
        </div>
        <div id="footer">
            Generated by <a href="https://github.com/petr-s/cleaREST">cleaREST</a> v0.3.
        </div>
    </body>
</html>"""), strip_ws(result))
